CHANGELOG.MD, assets/styles/settings/brand/_functions.scss, assets/styles/settings/brand/_typography.scss, assets/styles/theme-vesi.scss, assets/styles/ui-components/_button.scss, lib/ThemeCustomizationController.php
=> TMS-546: Add theme fonts

CHANGELOG.MD, lib/ThemeCustomizationController.php
=> TMS-621: 404 page

CHANGELOG.MD, assets/styles/theme-vesi.scss, assets/styles/ui-components/_footer.scss, assets/styles/ui-components/_sibling-navigation.scss, assets/styles/ui-components/index.scss
=> TMS-548: Sibling navigation

CHANGELOG.MD, assets/styles/theme-vesi.scss, assets/styles/ui-components/_breadcrumbs.scss, assets/styles/ui-components/index.scss, lib/ThemeCustomizationController.php, partials/ui/breadcrumbs.dust
=> TMS-549: Breadcrumbs

CHANGELOG.MD, assets/styles/layouts/_call-to-action.scss, assets/styles/layouts/index.scss, assets/styles/ui-components/_sibling-navigation.scss, assets/styles/ui-components/header/_language-nav.scss, lib/ACF/AlterCallToActionLayout.php, lib/ThemeCustomizationController.php, partials/layouts/layout-call-to-action.dust, partials/layouts/layout-hero.dust
=> TMS-595: Call to Action Layout

CHANGELOG.MD, assets/styles/main.scss, assets/styles/ui-components/index.scss, assets/styles/views/_page.scss, assets/styles/views/index.scss, partials/views/page/page-hero.dust
=> TMS-591: Page hero

CHANGELOG.MD, assets/styles/layouts/_hero.scss, lib/ACF/Fields/FaultMapFields.php, lib/ACF/Layouts/FaultMapLayout.php, lib/Blocks/FaultMapBlock.php, lib/BlocksController.php, lib/ThemeController.php, lib/ThemeCustomizationController.php, partials/blocks/block-fault-map.dust, partials/layouts/layout-fault-map.dust
=> TMS-592: Fault Map Block

CHANGELOG.MD, assets/styles/layouts/_link-list.scss, assets/styles/layouts/index.scss, partials/blocks/block-link-list.dust
=> TMS-603: Link list

CHANGELOG.MD, assets/styles/blocks/_grid.scss, assets/styles/blocks/index.scss, assets/styles/main.scss, assets/styles/settings/brand/_colors.scss, lib/ACF/Fields/FaultMapFields.php, lib/ACF/Fields/HeroFields.php, lib/ACF/Layouts/FaultMapLayout.php, lib/Formatters/GridFormatter.php, lib/Formatters/HeroFormatter.php, partials/blocks/block-grid-item--featured.dust
=> TMS-608: Grid

CHANGELOG.MD, assets/styles/blocks/_key-figures.scss, assets/styles/blocks/index.scss, assets/styles/settings/_settings.scss, lib/ThemeCustomizationController.php
Key Figures block styles
TMS-606
=> TMS-606: Key Figures

CHANGELOG.MD, assets/styles/blocks/_notice-banner.scss, assets/styles/blocks/index.scss, lib/Formatters/NoticeBannerFormatter.php, lib/ThemeCustomizationController.php, partials/blocks/block-notice-banner.dust
=> TMS-616: Notice Banner

CHANGELOG.MD, assets/styles/blocks/_grid.scss, package-lock.json, package.json, partials/layouts/layout-content-columns.dust
Content Columns Layout
TMS-607
=> TMS-607: Content Columns Layout

CHANGELOG.MD, assets/styles/blocks/_notice-banner.scss, assets/styles/blocks/_quote.scss, assets/styles/blocks/index.scss, lib/Formatters/NoticeBannerFormatter.php
=> TMS-601: Quote styles

CHANGELOG.MD, assets/scripts/theme-vesi.js, assets/styles/blocks/_image.scss, assets/styles/blocks/_share-links.scss, assets/styles/blocks/_subpages.scss, assets/styles/blocks/index.scss, package-lock.json, package.json, webpack.config.js
=> TMS-612: Share Links

CHANGELOG.MD, assets/styles/settings/brand/_typography.scss, assets/styles/ui-components/_breadcrumbs.scss, assets/styles/views/_page.scss, assets/styles/views/_single.scss, assets/styles/views/index.scss, partials/views/single/single-related.dust
=> TMS-611: Related posts styles

CHANGELOG.MD, assets/styles/blocks/_image.scss, assets/styles/ui-components/_breadcrumbs.scss, assets/styles/ui-components/_pagination.scss, assets/styles/ui-components/header/_fly-out-nav.scss, assets/styles/ui-components/index.scss, assets/styles/views/_search.scss, assets/styles/views/index.scss, lib/ThemeCustomizationController.php, partials/views/search/form-filters.dust, partials/views/search/results.dust, partials/views/search/search-term-input.dust
=> TMS-620: Search styles

CHANGELOG.MD, partials/layouts/layout-textblock.dust
=> TMS-617: Text Block Layout

CHANGELOG.MD, assets/styles/layouts/_articles.scss, assets/styles/ui-components/_highlight-article.scss, assets/styles/ui-components/index.scss, partials/views/home/home-grid-item.dust, partials/views/home/home-list-item.dust
=> TMS-588: Articles view

CHANGELOG.MD, assets/styles/blocks/_materials.scss, assets/styles/blocks/index.scss, partials/blocks/block-material.dust
=> TMS-589: Material block styles

CHANGELOG.MD, assets/styles/layouts/_logo-wall.scss, assets/styles/layouts/index.scss
=> TMS-596: Logo Wall

CHANGELOG.MD, assets/styles/blocks/_image.scss, assets/styles/views/_page-materials.scss, assets/styles/views/_page.scss, assets/styles/views/index.scss, package-lock.json, package.json, partials/material-page-item.dust, partials/material-type-term-list.dust, partials/page-materials.dust, webpack.config.js
=> TMS-599: Material Bank

CHANGELOG.MD, assets/styles/blocks/_table.scss, assets/styles/blocks/index.scss, assets/styles/theme-vesi.scss
=> TMS-602: Table styles

CHANGELOG.MD, assets/styles/blocks/_accordion.scss, assets/styles/blocks/index.scss
=> TMS-600: Accordion

.github/workflows/phpcs-check.yml, CHANGELOG.MD, assets/styles/layouts/_articles.scss, assets/styles/ui-components/_highlight-article.scss, assets/styles/views/_archive-blog-article.scss, assets/styles/views/_single-blog-article.scss, assets/styles/views/index.scss, comments.php, lib/ThemeCustomizationController.php, partials/archive-blog-article.dust
=> TMS-585: Single blog article

.github/dependabot.yml, CHANGELOG.MD, assets/styles/ui-components/_archive-filters.scss, assets/styles/ui-components/_modal.scss, assets/styles/ui-components/index.scss, assets/styles/views/_single-blog-article.scss, package-lock.json, partials/ui/menu/fly-out-nav.dust, partials/views/single-blog-article/blog-info.dust
=> TMS-609: Modal styles

CHANGELOG.MD, assets/styles/blocks/_contacts.scss, assets/styles/blocks/index.scss, assets/styles/ui-components/_archive-filters.scss, lib/ThemeCustomizationController.php, partials/shared/contact.dust
=> TMS-613: Contact block styles

CHANGELOG.MD, assets/styles/blocks/_accordion.scss, assets/styles/ui-components/_forms.scss, assets/styles/ui-components/index.scss, partials/blocks/block-accordion.dust, partials/page.dust, partials/shared/contact.dust
=> TMS-614: Forms

CHANGELOG.MD, assets/styles/blocks/_table.scss, assets/styles/layouts/_icon-links.scss, assets/styles/layouts/index.scss, assets/styles/theme-vesi.scss, assets/styles/ui-components/_button.scss, assets/styles/ui-components/_forms.scss, lib/GravityForms.php, lib/ThemeController.php, lib/ThemeCustomizationController.php, partials/blocks/block-image-gallery.dust, partials/layouts/layout-icon-links.dust
=> TMS-710: Icon links

CHANGELOG.MD, assets/styles/layouts/_hero.scss
CR: https://geniemdev.atlassian.net/browse/TMS-782
Change the hero height from desktop breakpoint up.
TMS-782
Local, stage.
=> TMS-782: Hero height change

CHANGELOG.MD, assets/styles/ui-components/header/_header-top.scss, lib/ThemeCustomizationController.php, partials/shared/header-notice.dust
CR: https://geniemdev.atlassian.net/browse/TMS-783
Add possibility to select alert mode for the exception notice.
TMS-783
Local, stage.
=> TMS-783: Exception notice alert mode

CHANGELOG.MD, lib/ACF/Fields/FaultMapFields.php, partials/page-materials.dust
=> TMS-731: add components to materials-page

CHANGELOG.MD, assets/styles/settings/_settings.scss, assets/styles/theme-vesi.scss
Body color to black
TMS-786
Local, staging
=> TMS-786: Body color to black

CHANGELOG.MD, partials/blocks/block-material.dust
=> TMS-839: Justify block content

partials/views/home/home-grid-item.dust, partials/views/home/home-list-item.dust
=> TMS-880: Display drupal image

CHANGELOG.MD, assets/styles/blocks/_table.scss
=> TMS-892: reduce table td min-width

CHANGELOG.MD, assets/styles/ui-components/header/_fly-out-nav.scss, partials/ui/menu/fly-out-nav.dust, partials/ui/search-form-small.dust, style.css
TASK: https://geniemdev.atlassian.net/browse/PIEN-8034
Changed single search-button that didn't have an input besides it to a search-form partial.
=> Pien-8034: Fix search in hamburger-menu

CHANGELOG.MD, lib/Formatters/PriceCalculatorPirkkalaFormatter.php, lib/Formatters/PriceCalculatorTampereFormatter.php, style.css
TASK: https://geniemdev.atlassian.net/browse/PIEN-8111
Change price calculator values
=> Pien-8111: Change price calculator values

CHANGELOG.MD, partials/views/single/single-related.dust
CR: https://geniemdev.atlassian.net/browse/PIEN-8606
Display API images
PIEN-8606
=> PIEN-8606: Display API images

CHANGELOG.MD, lib/Formatters/PriceCalculatorPirkkalaFormatter.php, lib/Formatters/PriceCalculatorTampereFormatter.php, style.css
TMS-1003: Update price calculator values
=> TMS-1003: Update price calculator values

CHANGELOG.MD, lib/Formatters/PriceCalculatorPirkkalaFormatter.php
TMS-1005: Fix Pirkkala calculator total price
=> TMS-1005: Fix Pirkkala calculator total price
